name: create-config.json
on:
  push:
    branches:
      - main
jobs:
  creating-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node .github/workflows/check-files.js
  publishing-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'http://npm.pkg.github.com'
          scope: '@wellwelwel'
      - run: node .github/workflows/publish.js
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}